import type { LucideIcon } from "lucide-react";

// ---------------------------------------------------------------------------
// Layout / Navigation
// ---------------------------------------------------------------------------

export interface NavItem {
  href: string;
  label: string;
  icon: LucideIcon;
}

// ---------------------------------------------------------------------------
// Challenge / Proposal types (shared across Tab 2 and Tab 3)
// ---------------------------------------------------------------------------

export type VisualizationType =
  | "flow"
  | "before-after"
  | "metrics"
  | "architecture"
  | "risk-matrix"
  | "timeline"
  | "dual-kpi"
  | "tech-stack"
  | "decision-flow";

export interface Challenge {
  id: string;
  title: string;
  description: string;
  visualizationType: VisualizationType;
  outcome?: string;
}

export interface Profile {
  name: string;
  tagline: string;
  bio: string;
  approach: { title: string; description: string }[];
  skillCategories: { name: string; skills: string[] }[];
}

export interface PortfolioProject {
  id: string;
  title: string;
  description: string;
  tech: string[];
  relevance?: string;
  outcome?: string;
  liveUrl?: string;
}

// Screen definition for mobile-app-preview frame format
export interface DemoScreen {
  id: string;
  label: string;
  icon?: LucideIcon;
  href: string;
}

// Conversion element variant types
export type ConversionVariant = "sidebar" | "inline" | "floating" | "banner";

// ---------------------------------------------------------------------------
// Creator Marketplace — Domain Types
// ---------------------------------------------------------------------------

// -- Creator (Seller) -------------------------------------------------------

export type CreatorStatus =
  | "Active"
  | "New Creator"
  | "Top Seller"
  | "On Vacation"
  | "Under Review"
  | "Suspended"
  | "Verified";

export interface Creator {
  id: string;
  /** Creator's real name */
  name: string;
  /** Their branded shop name displayed to buyers */
  shopName: string;
  avatarUrl: string;
  location: string;
  memberSince: string; // ISO date string
  status: CreatorStatus;
  /** Verified identity badge */
  isVerified: boolean;
  /** Top 5% GMV earners */
  isTopSeller: boolean;
  /** Average star rating across all completed orders; null for new shops with zero reviews */
  starRating: number | null;
  totalReviews: number;
  totalListings: number;
  activeListings: number;
  followers: number;
  /** Total earnings this calendar month (post-fee) */
  earningsThisMonth: number;
  /** Total lifetime GMV generated by this shop */
  lifetimeGmv: number;
  /** Seller's payout balance currently available */
  availableBalance: number;
  /** Payout funds currently on hold pending dispute resolution */
  balanceOnHold: number;
  processingTimeDays: string; // e.g. "1–3 business days"
  bio: string;
}

// -- Listing ----------------------------------------------------------------

export type ListingStatus =
  | "Active"
  | "Draft"
  | "Paused"
  | "Sold Out"
  | "Expired"
  | "Removed";

export type ListingCategory =
  | "Jewelry & Accessories"
  | "Home Decor"
  | "Clothing & Vintage"
  | "Art & Prints"
  | "Ceramics & Pottery"
  | "Candles & Fragrance"
  | "Textiles & Fiber"
  | "Leather Goods"
  | "Digital Downloads"
  | "Stationery & Paper";

export interface Listing {
  id: string;
  creatorId: string;
  title: string;
  category: ListingCategory;
  status: ListingStatus;
  price: number; // USD
  /** Original price before any active sale, null if not on sale */
  originalPrice: number | null;
  /** True if a timed sale is currently active */
  onSale: boolean;
  quantity: number; // 0 = Sold Out
  /** Mock image URL placeholder referencing a product color theme */
  imageColor: string; // tailwind bg color token for placeholder
  /** Number of listing page views this month */
  views: number;
  /** Number of shoppers who saved/favorited this listing */
  saves: number;
  /** Number of orders fulfilled from this listing */
  orders: number;
  createdAt: string;
  /** ISO date — Etsy-style 120-day listing expiry */
  expiresAt: string;
  /** Flagged for high views with zero conversions — signals pricing/photo issue */
  conversionAlert: boolean;
  isDigitalDownload: boolean;
  tags: string[];
}

// -- Order ------------------------------------------------------------------

export type OrderStatus =
  | "Processing"
  | "Shipped"
  | "Out for Delivery"
  | "Delivered"
  | "Disputed"
  | "Refunded"
  | "Cancelled"
  | "Pending Payment";

export type ShippingCarrier = "USPS" | "UPS" | "FedEx" | "DHL";

export interface Order {
  id: string;
  /** Human-readable order reference shown to buyers and creators */
  orderNumber: string;
  creatorId: string;
  listingId: string;
  listingTitle: string;
  /** Snapshot of the listing image color at time of purchase */
  listingImageColor: string;
  buyerName: string;
  buyerLocation: string;
  status: OrderStatus;
  quantity: number;
  subtotal: number; // order item total
  shippingCost: number;
  /** Platform commission deducted from creator payout */
  platformFee: number;
  /** Amount creator actually receives */
  creatorEarnings: number;
  /** Tax collected by platform on behalf of state */
  taxCollectedByPlatform: number;
  carrier: ShippingCarrier | null;
  trackingNumber: string | null;
  /** ISO date — estimated delivery date shown to buyer */
  estimatedDelivery: string | null;
  /** ISO date — actual delivery confirmation */
  actualDelivery: string | null;
  /** Days creator needs before shipping (separate from transit time) */
  processingTimeDays: number;
  /** Present only when status === "Disputed" */
  disputeReason: string | null;
  /** Note for refunded or cancelled orders */
  resolutionNote: string | null;
  placedAt: string;
  shippedAt: string | null;
}

// -- Payout -----------------------------------------------------------------

export type PayoutStatus = "Scheduled" | "Processing" | "Paid" | "On Hold" | "Failed";

export interface Payout {
  id: string;
  creatorId: string;
  status: PayoutStatus;
  amount: number;
  /** Gross GMV that generated this payout before fees */
  grossAmount: number;
  platformFee: number;
  /** ISO date — when funds are expected to arrive */
  scheduledDate: string;
  /** ISO date — when funds actually cleared, null if not yet paid */
  paidDate: string | null;
  /** Reason for hold; present only when status === "On Hold" */
  holdReason: string | null;
  /** Estimated hold release date; present when status === "On Hold" */
  holdReleaseDate: string | null;
  orderCount: number;
  period: string; // e.g. "Feb 1–14, 2026"
}

// -- Review -----------------------------------------------------------------

export interface ShopReview {
  id: string;
  orderId: string;
  creatorId: string;
  buyerName: string;
  /** 1–5 star rating */
  rating: number;
  comment: string;
  /** Date the buyer left the review */
  reviewedAt: string;
  /** Creator's optional public response */
  creatorResponse: string | null;
  listingTitle: string;
}

// -- Buyer ------------------------------------------------------------------

export interface Buyer {
  id: string;
  name: string;
  location: string;
  joinedAt: string;
  totalOrders: number;
  totalSpent: number;
  /** True if buyer has placed 2+ orders */
  isRepeatBuyer: boolean;
  savedListings: number;
  followedShops: number;
}

// -- Dashboard / KPI --------------------------------------------------------

export interface DashboardStats {
  /** Gross Merchandise Value this month */
  gmvThisMonth: number;
  /** % change vs prior month */
  gmvChange: number;
  /** Creator's net earnings after platform fee, this month */
  earningsThisMonth: number;
  earningsChange: number;
  /** Active (published) listings count */
  activeListings: number;
  activeListingsChange: number;
  /** Orders received this month */
  ordersThisMonth: number;
  ordersChange: number;
  /** Average order value this month */
  aov: number;
  aovChange: number;
  /** Shop star rating (weighted avg) */
  starRating: number;
  /** Order-to-listing-view conversion rate (%) */
  conversionRate: number;
  conversionRateChange: number;
  /** Payout balance available for withdrawal */
  availableBalance: number;
  /** Funds on hold */
  balanceOnHold: number;
}

// -- Chart Data -------------------------------------------------------------

export interface EarningsDataPoint {
  month: string;
  earnings: number;
  gmv: number;
  orders: number;
}

export interface ListingCategoryBreakdown {
  category: string;
  listingCount: number;
  gmv: number;
  conversionRate: number;
}

export interface OrderStatusBreakdown {
  status: OrderStatus;
  count: number;
  percentage: number;
}

// Star Seller progress tracker
export interface StarSellerCriteria {
  label: string;
  met: boolean;
  value: string;
  target: string;
}
